### PR TITLE
Alpha build

### PR DESCRIPTION
**Pull request by jakubfiala**
This PR is not as daunting as it seems. most of the 2000 additions are JSON schemas which won't change much and contain a lot of repetition.

### CODE REVIEW

**Comment by kenoir** [comment]
You could build this in Circle and deploy from there which would allow you to remove the compiled assets.

**Comment by jakubfiala** [comment]
@kenoir yeah that sounds fair. maybe I could also get rid of the schemas in the repo somehow …

**Comment by jakubfiala** [comment]
although schemas may be useful to track with git

**Comment by jakubfiala** [comment]
I'm just going to merge this after the CI passes …

**Pull request merged**
